# Generated by Django 5.1.15 on 2026-09-07 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curriculum", "0002_appsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoadmapEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("university", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        help_text="The foreign programme's own grouping — the reference view groups by university then this.",
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="The foreign course's código, verbatim.",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The foreign course's name, verbatim.", max_length=300
                    ),
                ),
                ("official_link", models.URLField(blank=True, default="")),
                ("video_link", models.URLField(blank=True, default="")),
                (
                    "youtube_channel",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("textbook", models.CharField(blank=True, default="", max_length=300)),
            ],
            options={
                "ordering": ["university", "category", "code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("university", "code"),
                        name="unique_roadmap_code_per_university",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CoverageLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("note", models.CharField(blank=True, default="", max_length=500)),
                (
                    "imported_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In progress"),
                            ("passed", "Passed"),
                            ("transferred", "Transferred"),
                            ("failed", "Failed"),
                        ],
                        default="",
                        help_text="Frozen status, used only when `course` is null. With a Course, its live Status wins and this is ignored.",
                        max_length=20,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coverage_links",
                        to="curriculum.course",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="reference.roadmapentry",
                    ),
                ),
            ],
            options={
                "ordering": ["entry", "position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entry", "position"),
                        name="unique_coverage_link_position_per_entry",
                    )
                ],
            },
        ),
    ]
