# Generated by Django 5.1.15 on 2026-09-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AvailabilityBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start", models.TimeField()),
                ("end", models.TimeField()),
                ("label", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["weekday", "start"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("start__lt", models.F("end"))),
                        name="availability_block_start_before_end",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StudyWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        unique=True,
                    ),
                ),
                ("start", models.TimeField()),
                ("end", models.TimeField()),
            ],
            options={
                "ordering": ["weekday"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("start__lt", models.F("end"))),
                        name="study_window_start_before_end",
                    )
                ],
            },
        ),
    ]
