# Generated by Django 5.1.15 on 2026-09-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoringConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "override_window_hours",
                    models.FloatField(
                        default=48.0,
                        help_text="A Graded Item due within this many hours can jump the queue.",
                    ),
                ),
                (
                    "override_min_weight",
                    models.FloatField(
                        default=0.1,
                        help_text="As a fraction of the full grade — a lighter item never triggers the Override (ADR-0008).",
                    ),
                ),
                (
                    "deadline_half_life_days",
                    models.FloatField(
                        default=7.0,
                        help_text="Days over which Deadline Pressure from an item halves.",
                    ),
                ),
                ("w_hours_behind", models.FloatField(default=1.0)),
                ("w_deadline", models.FloatField(default=20.0)),
                (
                    "stale_after_days",
                    models.PositiveSmallIntegerField(
                        default=4,
                        help_text="Days since the last Study Log after which the banner labels its recommendation a guess. Never suppresses it.",
                    ),
                ),
                ("difficulty_easy", models.FloatField(default=0.75)),
                ("difficulty_normal", models.FloatField(default=1.0)),
                ("difficulty_hard", models.FloatField(default=1.5)),
            ],
        ),
    ]
