# Generated by Django 5.1.15 on 2026-09-07 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curriculum", "0002_appsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In progress"),
                            ("passed", "Passed"),
                            ("transferred", "Transferred"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "final_grade",
                    models.FloatField(
                        blank=True,
                        help_text="Historical grade for display only — recorded for a Course passed/failed before this app existed. Never set for TRANSFERRED.",
                        null=True,
                    ),
                ),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_record",
                        to="curriculum.course",
                    ),
                ),
            ],
        ),
    ]
