# Generated by Django 5.1.15 on 2026-09-07 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studying", "0002_term_enrollment"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                (
                    "weight",
                    models.FloatField(
                        help_text="Share of the Course Grade, in the same units as the Program's grade_scale_max."
                    ),
                ),
                ("due_at", models.DateField(blank=True, null=True)),
                (
                    "grade",
                    models.FloatField(
                        blank=True,
                        help_text="The mark once earned; null until the grade arrives.",
                        null=True,
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graded_items",
                        to="studying.enrollment",
                    ),
                ),
            ],
            options={
                "ordering": ["due_at", "id"],
            },
        ),
    ]
