# Generated by Django 5.1.15 on 2026-09-07 16:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studying", "0003_gradeditem"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hours", models.FloatField()),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Where the student left off — handed back by the next Recommendation for this Course.",
                        max_length=500,
                    ),
                ),
                (
                    "studied_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_logs",
                        to="studying.enrollment",
                    ),
                ),
            ],
            options={
                "ordering": ["-studied_on", "-recorded_at"],
            },
        ),
    ]
