# Generated by Django 5.1.15 on 2026-09-07 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("country", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'IIC-2026' — distinguishes this Plan from a later revision of the same Program.",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "ordering": ["program", "name"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=200)),
                ("credits", models.PositiveSmallIntegerField()),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="curriculum.institution",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="e.g. 'A'", max_length=50)),
                (
                    "credits",
                    models.PositiveSmallIntegerField(
                        help_text="Declared total; loadplan rejects a mismatch against the sum of this Block's entries."
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="curriculum.plan",
                    ),
                ),
            ],
            options={
                "ordering": ["plan", "name"],
            },
        ),
        migrations.CreateModel(
            name="Prerequisite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="curriculum.course",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerequisites",
                        to="curriculum.plan",
                    ),
                ),
                (
                    "requires_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="curriculum.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("pass_mark", models.PositiveSmallIntegerField()),
                ("hours_per_credit", models.FloatField()),
                ("grade_scale_max", models.PositiveSmallIntegerField()),
                ("term_type", models.CharField(max_length=50)),
                ("term_weeks", models.PositiveSmallIntegerField()),
                ("terms_per_year", models.PositiveSmallIntegerField()),
                ("item_types", models.JSONField(default=list)),
                (
                    "default_items",
                    models.JSONField(
                        default=list,
                        help_text="Starting skeleton for a Cuatrimestre's deadlines grid — never a constraint. Each item: {type, weight}.",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="curriculum.institution",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="plan",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plans",
                to="curriculum.program",
            ),
        ),
        migrations.CreateModel(
            name="BlockEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credits", models.PositiveSmallIntegerField()),
                (
                    "slot_label",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("slot_index", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="curriculum.block",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="block_entries",
                        to="curriculum.course",
                    ),
                ),
            ],
            options={
                "ordering": ["block", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("course__isnull", False)),
                        fields=("block", "course"),
                        name="unique_named_entry_per_block",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("course__isnull", True)),
                        fields=("block", "slot_label", "slot_index"),
                        name="unique_slot_per_block",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("institution", "code"),
                name="unique_course_code_per_institution",
            ),
        ),
        migrations.AddConstraint(
            model_name="block",
            constraint=models.UniqueConstraint(
                fields=("plan", "name"), name="unique_block_name_per_plan"
            ),
        ),
        migrations.AddConstraint(
            model_name="prerequisite",
            constraint=models.UniqueConstraint(
                fields=("plan", "course", "requires_course"),
                name="unique_prerequisite_edge",
            ),
        ),
        migrations.AddConstraint(
            model_name="plan",
            constraint=models.UniqueConstraint(
                fields=("program", "name"), name="unique_plan_name_per_program"
            ),
        ),
    ]
